package com.hhj.seckill.entry;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;

@Data
@AllArgsConstructor
@NoArgsConstructor
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class OrderDetail implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.order_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.user_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.product_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.product_num
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.product_price
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Double productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.order_time
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Long orderTime;

    private String productName;

    private String productPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private static final long serialVersionUID = 1L;


}