package com.hhj.seckill.entry;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import java.io.Serializable;
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_title
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private String productTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_picture
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private String productPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_price
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private Double productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_selling_price
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private Double productSellingPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_num
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_intro
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private String productIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_title
     *
     * @return the value of product.product_title
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public String getProductTitle() {
        return productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_title
     *
     * @param productTitle the value for product.product_title
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductTitle(String productTitle) {
        this.productTitle = productTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_picture
     *
     * @return the value of product.product_picture
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public String getProductPicture() {
        return productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_picture
     *
     * @param productPicture the value for product.product_picture
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_price
     *
     * @return the value of product.product_price
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_price
     *
     * @param productPrice the value for product.product_price
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_selling_price
     *
     * @return the value of product.product_selling_price
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public Double getProductSellingPrice() {
        return productSellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_selling_price
     *
     * @param productSellingPrice the value for product.product_selling_price
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductSellingPrice(Double productSellingPrice) {
        this.productSellingPrice = productSellingPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_num
     *
     * @return the value of product.product_num
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_num
     *
     * @param productNum the value for product.product_num
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_intro
     *
     * @return the value of product.product_intro
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public String getProductIntro() {
        return productIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_intro
     *
     * @param productIntro the value for product.product_intro
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    public void setProductIntro(String productIntro) {
        this.productIntro = productIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Sun Feb 20 20:29:03 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", productTitle=").append(productTitle);
        sb.append(", productPicture=").append(productPicture);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", productSellingPrice=").append(productSellingPrice);
        sb.append(", productNum=").append(productNum);
        sb.append(", productIntro=").append(productIntro);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}