package com.hhj.seckill.entry;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import java.io.Serializable;
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class ProductPicture implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.id
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.product_id
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    private String productPicture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_picture.intro
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.id
     *
     * @return the value of product_picture.id
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.id
     *
     * @param id the value for product_picture.id
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.product_id
     *
     * @return the value of product_picture.product_id
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.product_id
     *
     * @param productId the value for product_picture.product_id
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.product_picture
     *
     * @return the value of product_picture.product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public String getProductPicture() {
        return productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.product_picture
     *
     * @param productPicture the value for product_picture.product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public void setProductPicture(String productPicture) {
        this.productPicture = productPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_picture.intro
     *
     * @return the value of product_picture.intro
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_picture.intro
     *
     * @param intro the value for product_picture.intro
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", productPicture=").append(productPicture);
        sb.append(", intro=").append(intro);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}