package com.hhj.seckill.entry;

import java.io.Serializable;

public class ShoppingCart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.product_id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.product_type
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    private Integer productType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.num
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shopping_cart
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.id
     *
     * @return the value of shopping_cart.id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.id
     *
     * @param id the value for shopping_cart.id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.product_id
     *
     * @return the value of shopping_cart.product_id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.product_id
     *
     * @param productId the value for shopping_cart.product_id
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.product_type
     *
     * @return the value of shopping_cart.product_type
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public Integer getProductType() {
        return productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.product_type
     *
     * @param productType the value for shopping_cart.product_type
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public void setProductType(Integer productType) {
        this.productType = productType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.num
     *
     * @return the value of shopping_cart.num
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.num
     *
     * @param num the value for shopping_cart.num
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbggenerated Mon Mar 07 15:43:39 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", productType=").append(productType);
        sb.append(", num=").append(num);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}