package com.hhj.seckill.entry;

import com.fasterxml.jackson.databind.PropertyNamingStrategy;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import java.io.Serializable;
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
public class UniOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.order_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.user_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.product_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.product_num
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.product_price
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Double productPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uni_order.order_time
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private Long orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.id
     *
     * @return the value of uni_order.id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.id
     *
     * @param id the value for uni_order.id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.order_id
     *
     * @return the value of uni_order.order_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.order_id
     *
     * @param orderId the value for uni_order.order_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.user_id
     *
     * @return the value of uni_order.user_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.user_id
     *
     * @param userId the value for uni_order.user_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.product_id
     *
     * @return the value of uni_order.product_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.product_id
     *
     * @param productId the value for uni_order.product_id
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.product_num
     *
     * @return the value of uni_order.product_num
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.product_num
     *
     * @param productNum the value for uni_order.product_num
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.product_price
     *
     * @return the value of uni_order.product_price
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public Double getProductPrice() {
        return productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.product_price
     *
     * @param productPrice the value for uni_order.product_price
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setProductPrice(Double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uni_order.order_time
     *
     * @return the value of uni_order.order_time
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public Long getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uni_order.order_time
     *
     * @param orderTime the value for uni_order.order_time
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    public void setOrderTime(Long orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", userId=").append(userId);
        sb.append(", productId=").append(productId);
        sb.append(", productNum=").append(productNum);
        sb.append(", productPrice=").append(productPrice);
        sb.append(", orderTime=").append(orderTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}