package com.hhj.seckill.mapper;

import com.hhj.seckill.entry.ProductPicture;
import com.hhj.seckill.entry.ProductPictureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductPictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int countByExample(ProductPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int deleteByExample(ProductPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int insert(ProductPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int insertSelective(ProductPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    List<ProductPicture> selectByExample(ProductPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    ProductPicture selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int updateByExampleSelective(@Param("record") ProductPicture record, @Param("example") ProductPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int updateByExample(@Param("record") ProductPicture record, @Param("example") ProductPictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int updateByPrimaryKeySelective(ProductPicture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_picture
     *
     * @mbggenerated Wed Mar 02 14:42:18 CST 2022
     */
    int updateByPrimaryKey(ProductPicture record);
}