package com.hhj.seckill.mapper;

import com.hhj.seckill.entry.SeckillProduct;
import com.hhj.seckill.entry.SeckillProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SeckillProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int countByExample(SeckillProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int deleteByExample(SeckillProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int deleteByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int insert(SeckillProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int insertSelective(SeckillProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    List<SeckillProduct> selectByExample(SeckillProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    SeckillProduct selectByPrimaryKey(Long seckillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int updateByExampleSelective(@Param("record") SeckillProduct record, @Param("example") SeckillProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int updateByExample(@Param("record") SeckillProduct record, @Param("example") SeckillProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int updateByPrimaryKeySelective(SeckillProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_product
     *
     * @mbggenerated Fri Mar 04 12:39:42 CST 2022
     */
    int updateByPrimaryKey(SeckillProduct record);
}