package com.hhj.seckill.mapper;

import com.hhj.seckill.entry.UniOrder;
import com.hhj.seckill.entry.UniOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UniOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int countByExample(UniOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int deleteByExample(UniOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int insert(UniOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int insertSelective(UniOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    List<UniOrder> selectByExample(UniOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    UniOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") UniOrder record, @Param("example") UniOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int updateByExample(@Param("record") UniOrder record, @Param("example") UniOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int updateByPrimaryKeySelective(UniOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uni_order
     *
     * @mbggenerated Fri Mar 11 21:09:47 CST 2022
     */
    int updateByPrimaryKey(UniOrder record);
}